// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6t-jfnAnpo1X5egVikVo_UBJ445fek2s',
    appId: '1:1002069294027:web:d652501dcfa0e829ec544e',
    messagingSenderId: '1002069294027',
    projectId: 'cricker-11204',
    authDomain: 'cricker-11204.firebaseapp.com',
    databaseURL: 'https://cricker-11204-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cricker-11204.appspot.com',
    measurementId: 'G-FKN3Y9NJRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbai1aXKz9RLvRssvqiinaQGgzuU90dqk',
    appId: '1:1002069294027:android:7aa8316e0834b078ec544e',
    messagingSenderId: '1002069294027',
    projectId: 'cricker-11204',
    databaseURL: 'https://cricker-11204-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cricker-11204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYpqVNV4MzkF-ebWA0OeYdiScXoI8QgVw',
    appId: '1:1002069294027:ios:4994ec8bc321beb8ec544e',
    messagingSenderId: '1002069294027',
    projectId: 'cricker-11204',
    databaseURL: 'https://cricker-11204-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cricker-11204.appspot.com',
    iosClientId: '1002069294027-fmslmp446c98jau63dfhqgaunouul6to.apps.googleusercontent.com',
    iosBundleId: 'com.example.cricker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYpqVNV4MzkF-ebWA0OeYdiScXoI8QgVw',
    appId: '1:1002069294027:ios:4994ec8bc321beb8ec544e',
    messagingSenderId: '1002069294027',
    projectId: 'cricker-11204',
    databaseURL: 'https://cricker-11204-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cricker-11204.appspot.com',
    iosClientId: '1002069294027-fmslmp446c98jau63dfhqgaunouul6to.apps.googleusercontent.com',
    iosBundleId: 'com.example.cricker',
  );
}
